"""link scholarship to uni instead of program

Revision ID: 0ddd5c436ce0
Revises: 8aa079a5142c
Create Date: 2021-05-11 15:43:00.365843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddd5c436ce0'
down_revision = '8aa079a5142c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('university_id', sa.Integer(), nullable=False))
    op.drop_constraint('scholarship_program_id_fkey', 'scholarship', type_='foreignkey')
    op.create_foreign_key(None, 'scholarship', 'university', ['university_id'], ['id'])
    op.drop_column('scholarship', 'program_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.create_foreign_key('scholarship_program_id_fkey', 'scholarship', 'program', ['program_id'], ['id'])
    op.drop_column('scholarship', 'university_id')
    # ### end Alembic commands ###
