"""add address

Revision ID: 3c08dce4336b
Revises: b02a2e1596fd
Create Date: 2021-05-11 19:19:42.341001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c08dce4336b'
down_revision = 'b02a2e1596fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campus', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campus', 'address')
    # ### end Alembic commands ###
