"""collect contact us data

Revision ID: 65658f0a0f5b
Revises: 3c08dce4336b
Create Date: 2021-05-12 12:22:18.919460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65658f0a0f5b'
down_revision = '3c08dce4336b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_item')
    # ### end Alembic commands ###
