"""Initial migration

Revision ID: 8aa079a5142c
Revises: 570edac5669c
Create Date: 2021-05-11 15:28:27.953953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa079a5142c'
down_revision = '570edac5669c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('locations', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
