"""add about ot uni

Revision ID: ef2006036e5c
Revises: 0ddd5c436ce0
Create Date: 2021-05-11 15:56:53.030980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2006036e5c'
down_revision = '0ddd5c436ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'about')
    # ### end Alembic commands ###
